### ISSUE TITLE
Can VFItoolkit deal with opitimal Ramsey policy problem?

### ISSUE THREAD

**Issue by dingliumath** [vfitoolkit/VFItoolkit-matlab-examples#1]
Dear Robert,
Thanks a lot for sharing this fantastic toolbox. I am wondering whether VFItoolkit can solve opitimal Ramsey policy problem. For this kind of problem in its simplest version, the benevolent government chooses policies to maximize social welfare (i.e. the representative household's lifetime utility) subject to private sector's optimality conditions and the resource contraint. If possible, how should we set up the return function in this case?

Best, 
Ding

**Comment by robertdkirkby** [comment]
You certainly could, but there is currently no specific command to do so.

In the most general case you need to solve an optimization problem wrapped around the general equilibrium problem. (whether you do this as nested optimization or joint optimization is likely unimportant for most models)

If you send a more specific description of the Ramsey problem you want to solve I can take a look at whether you would want to include the constraints inside the return fn, or just as an extra constraint in the general equilibrium problem (the later will work for most Ramsey problems). [feel free to email me the specific model: robertdkirkby@gmail.com]

**Comment by robertdkirkby** [comment]
ps. this is not really a bug/issue so the Discourse forum on the vfitoolkit.com website would probably be better place to ask it. But let's stick to github for now since it is already here.

**Comment by dingliumath** [comment]
Dear Robert,
Thanks a lot for your time and the link for vfitoolkit.com.
I have sent an e-mail to your gmail.

Best wishes,

Ding



Ding Liu
Associate Professor
School of Economics
Southwestern University of Finance and Economics (SWUFE)
Chengdu, China
Post code: 611130
E-mail: dingliumath@gmail.com
Homepage: https://sites.google.com/site/dingliumath

**Comment by robertdkirkby** [comment]
resolved over email
